### ISSUE TITLE
Filtering support

### ISSUE THREAD

**Issue by vaygr** [sapslaj/morbius#13]
It would be nice to have some sort of filtering support:

```yaml
  filter:
    - local-to-local: true
    - match: source_ip
      is: 0.0.0.0
    - match: source_ip
      is: 255.255.255.255
    - match: destination_ip
      is: 0.0.0.0
    - match: destination_ip
      is: 255.255.255.255
```

I'm also wondering if there's a way to make it more flexible, so you could use full ranges / subnets.
