### ISSUE TITLE
Add interface mapping enricher

### ISSUE THREAD

**Issue by vaygr** [sapslaj/morbius#7]
It would be handy to have interface names in metrics.

This could look like a simple map in yaml:

```yaml
…
  interface_mapper:
    0: igb0
    1: igb1
```

with fields: `in_interface_name`, `out_interface_name`.

**Comment by sapslaj** [comment]
Interesting idea! I could see this being expandable for several fields and not just interfaces and calling it like `field_mapper` or something so you aren't just limited to interfaces, especially for things like `sampler_address` if you have multiple routers sending flows to a central Morbius instance. Could even be kinda loosely based on Prometheus `relabel_configs`.

```yaml
  field_mapper:
    fields:
      - source_field: in_interface
        target_field: in_interface_name
        mapping: &interface_mapping
          0: igb0
          1: igb1
      - source_field: out_interface
        target_field: out_interface_name
        mapping: *interface_mapping
```

That's definitely a lot more verbose than your example, but technically more flexible.

There's also an existing precedent for using `text/template` in the config so that could also be an optional thing if you wanna get really advanced.

```yaml
      - source_field: sampler_address
        target_field: sampler_name
        mapping:
          10.0.0.1: router1
          10.0.0.2: router2
      - source_field: out_interface
        target_field: out_interface_name
        template: &interface_template >
          {{ if eq .Msg.sampler_name "router1" }}
          igb{{ .SourceField }}
          {{ else if eq .Msg.sampler_name "router2" }}
          eth{{ .SourceField }}
          {{ end }}
      - source_field: in_interface
        target_field: in_interface_name
        template: *interface_template
```

Another consideration: the enrichers are initialized and executed in a certain order: https://github.com/sapslaj/morbius/blob/c751d232737e39ecf26cf09d869405fd3261fa4e/config/config.go#L68-L87
https://github.com/sapslaj/morbius/blob/c751d232737e39ecf26cf09d869405fd3261fa4e/transport/transport.go#L115-L117

I guess it would make sense to have something like this be at the end of the pipeline so you could potentially override labels as needed.
